### ISSUE TITLE
Creation of build pipeline

### ISSUE THREAD

**Issue by peakwinter** [savoirfairelinux/sflvault-server#3]
Set up a Travis CI configuration file with the following elements:

For commits and pull requests to all branches (except `master`)
* Build a Docker container
* Run tests

For commits on `v2` branch:
* Build a Docker container
* Run tests
* Deploy container to Docker Hub on success (if v2 branch)

**Comment by peakwinter** [comment]
This is mostly done now, we just need to automate the pushing of new containers to the Docker Hub once the tests pass. 👍

**Comment by erozqba** [comment]
@peakwinter that is also done, check at https://hub.docker.com/r/savoirfairelinux/sflvault-server/
I have added you to the organization savoirfairelinux so you can modify that too.
