### ISSUE TITLE
Establish frontend framework and build system to use

### ISSUE THREAD

**Issue by peakwinter** [savoirfairelinux/sflvault-server#5]
The application will have a web interface, allowing for admin users to log in and manage available users, groups, clients/machines/services, etc.

This interface will use the Django multi-page app rendering system. We need to decide which frontend (HTML/CSS/JS) frameworks to use with this, and how they should be built and integrated into the application.

**Comment by maximeconnolly** [comment]
Closed in favor of build a client side application with the REST API.
